<a href="https://colab.research.google.com/github/Kasrakko/PyTorch-Deep-Learning/blob/main/NN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# GPU Info
!nvidia-smi

Mon Jan 30 09:28:28 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P0    31W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
# Basics Imports
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## **Tensors**

### Creating tensor

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:

scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([4,4])
vector

tensor([4, 4])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
matrix = torch.tensor([[4,5],
                      [6,9]])
matrix

tensor([[4, 5],
        [6, 9]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor 
tensor = torch.tensor([[[1,2,3],
                        [5,6,7],
                        [8,9,10]]])
tensor

tensor([[[ 1,  2,  3],
         [ 5,  6,  7],
         [ 8,  9, 10]]])

In [14]:
print(f"Dimentions of matrix {tensor.ndim}")
print(f"Shape of matrix {tensor.shape}")

Dimentions of matrix 3
Shape of matrix torch.Size([1, 3, 3])


### Random tensors

In [15]:
# Create a random tensor of size and shape
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9594, 0.9211, 0.1978, 0.8588],
        [0.9637, 0.3681, 0.9824, 0.6580],
        [0.7890, 0.4114, 0.9928, 0.6578]])

In [16]:
random_tensor.size()

torch.Size([3, 4])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))#height, weight, colour chaneles
print(f"Dimentions of matrix {random_image_size_tensor.ndim}")
print(f"Shape of matrix {random_image_size_tensor.shape}")

Dimentions of matrix 3
Shape of matrix torch.Size([224, 224, 3])


### Zeros and ones

In [18]:
# Create zeroes tensor
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create tensor of ones
ones = torch.ones(4,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### Creating a range of tensor and tensor-like

In [20]:
# Use torch.range()\arange()
torch.arange(0,101, 5) # torch.arange(start, end, step)

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100])

In [21]:
# Creating tensor like
zeros_tensor_like = torch.zeros_like(input=torch.arange(0,101, 5))
zeros_tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatype is one of the three big errors with pytorch and deeplearning
1. Tensors not right datatype  `tensor.dtype`
2. Tensors not right shape `tensor.shape`
3. tensors not on the right device   `tensor.device`

In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 5.0, 9.0],
                               dtype=None, # What dtype is the tensor
                               device=None, # What device is tensor on it
                               requires_grad=False # if you want pytorch track your gradient or not
                               )
float_32_tensor

tensor([3., 5., 9.])

In [23]:
float_64_tensor = float_32_tensor.type(torch.double) * float_32_tensor.type(torch.double)
float_64_tensor

tensor([ 9., 25., 81.], dtype=torch.float64)

### Manipulating tensors (tensor opratins)

Tensor oprations :
  * Addition
  * Subtraction
  * Multiplication
  * Division
  * Matrix multiplicatin

In [24]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [25]:
# Check with rand
tensor = torch.rand(4, 3)
tensor = tensor + 10
tensor

tensor([[10.3112, 10.4161, 10.2064],
        [10.0585, 10.0432, 10.8825],
        [10.5590, 10.1491, 10.9928],
        [10.9311, 10.6867, 10.8350]])

In [26]:
# Multiplying tensor
tensor = tensor * 100
tensor

tensor([[1031.1191, 1041.6097, 1020.6439],
        [1005.8535, 1004.3164, 1088.2465],
        [1055.9033, 1014.9092, 1099.2782],
        [1093.1072, 1068.6677, 1083.5005]])

In [27]:
# Subtraction
tensor = tensor - 10
tensor

tensor([[1021.1191, 1031.6097, 1010.6439],
        [ 995.8535,  994.3164, 1078.2465],
        [1045.9033, 1004.9092, 1089.2782],
        [1083.1072, 1058.6677, 1073.5005]])

In [28]:
# Try with pytorch built-in functions
tensor = torch.mul(tensor, 10)
tensor

tensor([[10211.1914, 10316.0977, 10106.4395],
        [ 9958.5342,  9943.1641, 10782.4648],
        [10459.0332, 10049.0918, 10892.7822],
        [10831.0723, 10586.6777, 10735.0049]])

***Note***

Learn more about built-in functions

### Matrix multiplying
* Two main ways to do this in deeplearning
  * Element-wise multiplication
  * Matrix multiplication (Dot product)
These are two main rules that performing mtrix multiplication needs to satisfy:
  * the **iner dimensions** must match:
    * `(3, 2) @ (3, 2)` wont work
    * `(2, 3) @ (3, 2)` will work
    * `(3, 2) @ (2, 3)` will work
  * The resulting matrix has the shape of the **outer dimension**
    * `(2, 3) @ (3, 2)` -> `(2, 2)`
    * `(3, 2) @ (2, 3)` -> `(3, 3)`

In [29]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.5777, 0.3670, 0.2484],
        [0.1973, 0.1290, 0.0410],
        [0.3222, 0.1686, 0.5704]])

In [30]:
# Element-wise 
tensor = torch.tensor([10, 20, 30])
print({tensor * tensor})
print({tensor * 10})

{tensor([100, 400, 900])}
{tensor([100, 200, 300])}


In [31]:
# Matrix Multiplying
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.3 ms, sys: 0 ns, total: 1.3 ms
Wall time: 1.3 ms


tensor(1400)

In [32]:
# Code what happen by hand
10*10 + 20*20 + 30*30

1400

In [33]:
# With for loop
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 468 µs, sys: 70 µs, total: 538 µs
Wall time: 2.25 ms


tensor(1400)

### One of the the most common errors in deeplearning: **Shape error**

# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # `torch.matmul()` == `torch.mm()`

In [34]:
tensor_A.shape, tensor_B.shape

NameError: ignored

To fix our tensor sahpe issue we can minipulate one of our tensor using a **transpose**

A **transpose** switches the axes or Dimentions of a given tensor 

In [35]:
tensor_B.T, tensor_B.T.shape

NameError: ignored

In [36]:
 torch.mm(tensor_A, tensor_B.T).shape

NameError: ignored

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [37]:
# Create a tensor
x = torch.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [39]:
# Find mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
 #Input dtype must be either a floating point or complex dtype. Got: Long

(tensor(45.), tensor(45.))

In [40]:
  # Find the sum
  torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the posotional MIN & MAX

In [41]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
x[0]

tensor(0)

In [43]:
# Finding the position of min and max with argmin() and argmax()
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsequeezing tensors
* Reshaping - reshape an iput tensor to a defined shape
* View - Return a view of an input tensor of certian shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vStack)
** Note: ** there is also 'hStack' 
* Squuezing - remove all '1' dimensions from a tensor
* Unsqueezing - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted  (swapped) in a certain way

In [44]:
# Create a tensor
tensor = torch.arange(1, 11)
tensor.shape , tensor

(torch.Size([10]), tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [45]:
# Add an extra dimension
tensor_reshaped = tensor.reshape(1, 10)
tensor_reshaped_H = tensor.reshape(5, 2)
tensor_reshaped, tensor_reshaped.shape, tensor_reshaped_H
# shape '[1, 7]' is invalid for input of size 10

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 torch.Size([1, 10]),
 tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]))

*** Note: ***
when we have 10 elements we can reshape the tensor with every combination of multiplying number which are equal to 10.
like (1, 10), (2, 5), (5, 2), (10, 1)

In [46]:
# Change the view 
tensor_changed_view = tensor.view(1, 10)
tensor_changed_view

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [47]:
# Changing tensor_changed_view changes ***tensor*** (becuase a view of the tensor shares the same memory as the original input)
tensor_changed_view[:, 1] = 85
tensor_changed_view, tensor

(tensor([[ 1, 85,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 1, 85,  3,  4,  5,  6,  7,  8,  9, 10]))

In [48]:
# Stack funtion in torch
tensor_stacked = torch.stack([x, x, x, x])
tensor_stacked_with_dim = torch.stack([x, x, x, x], dim=1)
tensor_stacked, tensor_stacked_with_dim

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
         [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
         [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
         [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), tensor([[ 0,  0,  0,  0],
         [10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30],
         [40, 40, 40, 40],
         [50, 50, 50, 50],
         [60, 60, 60, 60],
         [70, 70, 70, 70],
         [80, 80, 80, 80],
         [90, 90, 90, 90]]))

In [49]:
  # torch.squeeze() -> removes all single dimension from a target tensor
tensor_reshaped

tensor([[ 1, 85,  3,  4,  5,  6,  7,  8,  9, 10]])

In [55]:
tensor_squeezed = tensor_reshaped.squeeze()
tensor_squeezed,tensor_squeezed.shape

(tensor([ 1, 85,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [59]:
print(f"tensor reshaped form = {tensor_reshaped} \n and the shape is {tensor_reshaped.shape}")
print(f"tensor reshaped squeezed = {tensor_squeezed} \n and the shape is {tensor_squeezed.shape}")

tensor reshaped form = tensor([[ 1, 85,  3,  4,  5,  6,  7,  8,  9, 10]]) 
 and the shape is torch.Size([1, 10])
tensor reshaped squeezed = tensor([ 1, 85,  3,  4,  5,  6,  7,  8,  9, 10]) 
 and the shape is torch.Size([10])


In [67]:
# Example with Unsqueezed -> add a single dimension to target tensor
tensor_reshaped_Unsqueezed_dim0 = tensor_reshaped.unsqueeze(dim=0)
tensor_reshaped_Unsqueezed_dim1 = tensor_reshaped.unsqueeze(dim=1)
print(f"tensor reshaped form = {tensor_reshaped} \n and the shape is {tensor_reshaped.shape}")
print(f"tensor reshaped squeezed = {tensor_reshaped_Unsqueezed_dim0} \n and the shape is {tensor_reshaped_Unsqueezed_dim0.shape}")
print(f"tensor reshaped squeezed = {tensor_reshaped_Unsqueezed_dim1} \n and the shape is {tensor_reshaped_Unsqueezed_dim1.shape}")

tensor reshaped form = tensor([[ 1, 85,  3,  4,  5,  6,  7,  8,  9, 10]]) 
 and the shape is torch.Size([1, 10])
tensor reshaped squeezed = tensor([[[ 1, 85,  3,  4,  5,  6,  7,  8,  9, 10]]]) 
 and the shape is torch.Size([1, 1, 10])
tensor reshaped squeezed = tensor([[[ 1, 85,  3,  4,  5,  6,  7,  8,  9, 10]]]) 
 and the shape is torch.Size([1, 1, 10])


In [79]:
# $Example with 3*4 dimension
tensor_new = torch.rand(3, 4)
tensor_new_Unsqueezed_dim0 = tensor_new.unsqueeze(dim=0)
tensor_new_Unsqueezed_dim1 = tensor_new.unsqueeze(dim=1)
tensor_new_Unsqueezed_dim2 = tensor_new.unsqueeze(dim=2)
print(f"tensor new form =\n {tensor_new} \n and the shape is {tensor_new.shape}\n")
print(f"tensor new squeezed with dim=0 =\n {tensor_new_Unsqueezed_dim0} \n and the shape is {tensor_new_Unsqueezed_dim0.shape}\n")
print(f"tensor new squeezed with dim=1 =\n {tensor_new_Unsqueezed_dim1} \n and the shape is {tensor_new_Unsqueezed_dim1.shape}\n")
print(f"tensor new squeezed with dim=2 =\n {tensor_new_Unsqueezed_dim2} \n and the shape is {tensor_new_Unsqueezed_dim2.shape}\n")

tensor new form =
 tensor([[0.4689, 0.9505, 0.1695, 0.3069],
        [0.7022, 0.0706, 0.0801, 0.2843],
        [0.1230, 0.6851, 0.0620, 0.1590]]) 
 and the shape is torch.Size([3, 4])

tensor new squeezed with dim=0 =
 tensor([[[0.4689, 0.9505, 0.1695, 0.3069],
         [0.7022, 0.0706, 0.0801, 0.2843],
         [0.1230, 0.6851, 0.0620, 0.1590]]]) 
 and the shape is torch.Size([1, 3, 4])

tensor new squeezed with dim=1 =
 tensor([[[0.4689, 0.9505, 0.1695, 0.3069]],

        [[0.7022, 0.0706, 0.0801, 0.2843]],

        [[0.1230, 0.6851, 0.0620, 0.1590]]]) 
 and the shape is torch.Size([3, 1, 4])

tensor new squeezed with dim=2 =
 tensor([[[0.4689],
         [0.9505],
         [0.1695],
         [0.3069]],

        [[0.7022],
         [0.0706],
         [0.0801],
         [0.2843]],

        [[0.1230],
         [0.6851],
         [0.0620],
         [0.1590]]]) 
 and the shape is torch.Size([3, 4, 1])



*** Note: ***

So when we add a single dimension to ***dim=0***, the math explenation is we add a big matrix to the whole matrix.

But when we add a single dimension to ***dim=1***, the math explenation is we add a single matrix to each raw of our matrix

In [84]:
# torch.permute() -> rearange the dimensions of the target tensor in a specified  order
tensor_image = torch.rand(224, 224, 3)

# Permute the dimensions
tensor_image_permuted = tensor_image.permute(2, 0, 1)
print(f"The original tensor of exaple image:\n{tensor_image}\n and the dimension is {tensor_image.shape}\n")
print(f"The permuted tensor of exaple image:\n{tensor_image_permuted}\n and the dimension is {tensor_image_permuted.shape}\n")
print("So we permute a [0, 1, 2] matrix dimesions to [2, 0, 1]")


The original tensor of exaple image:
tensor([[[0.0603, 0.5368, 0.9000],
         [0.3555, 0.2751, 0.9075],
         [0.1947, 0.0741, 0.1379],
         ...,
         [0.7104, 0.5801, 0.8449],
         [0.8788, 0.5613, 0.5476],
         [0.8714, 0.8797, 0.4299]],

        [[0.6367, 0.5599, 0.0637],
         [0.1489, 0.1619, 0.1610],
         [0.3105, 0.0041, 0.3407],
         ...,
         [0.3195, 0.0280, 0.0391],
         [0.4190, 0.8822, 0.1457],
         [0.5113, 0.4150, 0.7876]],

        [[0.2420, 0.3357, 0.0998],
         [0.2634, 0.9067, 0.1386],
         [0.4868, 0.3385, 0.6977],
         ...,
         [0.5054, 0.1870, 0.1086],
         [0.4953, 0.6963, 0.9278],
         [0.4911, 0.6636, 0.8384]],

        ...,

        [[0.4362, 0.5473, 0.0431],
         [0.2064, 0.8011, 0.4617],
         [0.0833, 0.1971, 0.7244],
         ...,
         [0.6992, 0.3330, 0.4892],
         [0.5053, 0.1254, 0.4847],
         [0.2267, 0.5472, 0.3805]],

        [[0.8122, 0.6964, 0.6621],
         [

In [90]:
tensor_image[0, 0, 0] = 85
tensor_image_permuted[0, 0, 0]
# So the permute is a view so any change on original will apllyed in permuted matrix

tensor(85.)

In [92]:
tensor_image_permuted[0, 0, 0] = 86
tensor_image[0, 0, 0]
# and its also true for opposite 

tensor(86.)