<a href="https://colab.research.google.com/github/Kasrakko/PyTorch-Deep-Learning/blob/main/Pytorch_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# GPU Info
!nvidia-smi

Sun Jan 29 15:40:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P0    25W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
# Basics Imports
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## **Tensors**

### Creating tensor

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:

scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([4,4])
vector

tensor([4, 4])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
matrix = torch.tensor([[4,5],
                      [6,9]])
matrix

tensor([[4, 5],
        [6, 9]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor 
tensor = torch.tensor([[[1,2,3],
                        [5,6,7],
                        [8,9,10]]])
tensor

tensor([[[ 1,  2,  3],
         [ 5,  6,  7],
         [ 8,  9, 10]]])

In [14]:
print(f"Dimentions of matrix {tensor.ndim}")
print(f"Shape of matrix {tensor.shape}")

Dimentions of matrix 3
Shape of matrix torch.Size([1, 3, 3])


### Random tensors

In [15]:
# Create a random tensor of size and shape
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5818, 0.6569, 0.8117, 0.8994],
        [0.4602, 0.5096, 0.2685, 0.3307],
        [0.8279, 0.3321, 0.2571, 0.6019]])

In [16]:
random_tensor.size()

torch.Size([3, 4])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))#height, weight, colour chaneles
print(f"Dimentions of matrix {random_image_size_tensor.ndim}")
print(f"Shape of matrix {random_image_size_tensor.shape}")

Dimentions of matrix 3
Shape of matrix torch.Size([224, 224, 3])


### Zeros and ones

In [18]:
# Create zeroes tensor
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create tensor of ones
ones = torch.ones(4,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### Creating a range of tensor and tensor-like

In [20]:
# Use torch.range()\arange()
torch.arange(0,101, 5) # torch.arange(start, end, step)

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100])

In [21]:
# Creating tensor like
zeros_tensor_like = torch.zeros_like(input=torch.arange(0,101, 5))
zeros_tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatype is one of the three big errors with pytorch and deeplearning
1. Tensors not right datatype  `tensor.dtype`
2. Tensors not right shape `tensor.shape`
3. tensors not on the right device   `tensor.device`

In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 5.0, 9.0],
                               dtype=None, # What dtype is the tensor
                               device=None, # What device is tensor on it
                               requires_grad=False # if you want pytorch track your gradient or not
                               )
float_32_tensor

tensor([3., 5., 9.])

In [23]:
float_64_tensor = float_32_tensor.type(torch.double) * float_32_tensor.type(torch.double)
float_64_tensor

tensor([ 9., 25., 81.], dtype=torch.float64)

### Manipulating tensors (tensor opratins)

Tensor oprations :
  * Addition
  * Subtraction
  * Multiplication
  * Division
  * Matrix multiplicatin

In [27]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
# Check with rand
tensor = torch.rand(4, 3)
tensor = tensor + 10
tensor

tensor([[10.4158, 10.6853, 10.4253],
        [10.8011, 10.6440, 10.3629],
        [10.4257, 10.9355, 10.6186],
        [10.8304, 10.1022, 10.8588]])

In [30]:
# Multiplying tensor
tensor = tensor * 100
tensor

tensor([[1041.5807, 1068.5278, 1042.5295],
        [1080.1134, 1064.4049, 1036.2935],
        [1042.5701, 1093.5497, 1061.8585],
        [1083.0367, 1010.2156, 1085.8826]])

In [32]:
# Subtraction
tensor = tensor - 10
tensor

tensor([[1021.5807, 1048.5278, 1022.5295],
        [1060.1134, 1044.4049, 1016.2935],
        [1022.5701, 1073.5497, 1041.8585],
        [1063.0367,  990.2156, 1065.8826]])

In [34]:
# Try with pytorch built-in functions
tensor = torch.mul(tensor, 10)
tensor

tensor([[10215.8066, 10485.2783, 10225.2949],
        [10601.1338, 10444.0488, 10162.9346],
        [10225.7012, 10735.4971, 10418.5850],
        [10630.3672,  9902.1562, 10658.8262]])

***Note***

Learn more about built-in functions

### Matrix multiplying
* Two main ways to do this in deeplearning
  * Element-wise multiplication
  * Matrix multiplication (Dot product)
These are two main rules that performing mtrix multiplication needs to satisfy:
  * the **iner dimensions** must match:
    * `(3, 2) @ (3, 2)` wont work
    * `(2, 3) @ (3, 2)` will work
    * `(3, 2) @ (2, 3)` will work
  * The resulting matrix has the shape of the **outer dimension**
    * `(2, 3) @ (3, 2)` -> `(2, 2)`
    * `(3, 2) @ (2, 3)` -> `(3, 3)`

In [50]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.5508, 0.4479, 0.8202],
        [0.2600, 0.2356, 0.4200],
        [0.4160, 0.4128, 0.7206]])

In [41]:
# Element-wise 
tensor = torch.tensor([10, 20, 30])
print({tensor * tensor})
print({tensor * 10})

{tensor([100, 400, 900])}
{tensor([100, 200, 300])}


In [45]:
# Matrix Multiplying
%%time
torch.matmul(tensor, tensor)

CPU times: user 123 µs, sys: 0 ns, total: 123 µs
Wall time: 127 µs


tensor(1400)

In [43]:
# Code what happen by hand
10*10 + 20*20 + 30*30

1400

In [46]:
# With for loop
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 189 µs, sys: 0 ns, total: 189 µs
Wall time: 193 µs


tensor(1400)

### One of the the most common errors in deeplearning: **Shape error**

In [51]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # `torch.matmul()` == `torch.mm()`

RuntimeError: ignored

In [53]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor sahpe issue we can minipulate one of our tensor using a **transpose**

A **transpose** switches the axes or Dimentions of a given tensor 

In [64]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [65]:
 torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [73]:
# Create a tensor
x = torch.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [75]:
# Find mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
 #Input dtype must be either a floating point or complex dtype. Got: Long

(tensor(45.), tensor(45.))

In [76]:
  # Find the sum
  torch.sum(x), x.sum()

(tensor(450), tensor(450))